# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/tts_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/tts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/tts_service.proto\x12\x06tts.v1\"\x89\x01\n\nTTSRequest\x12#\n\x04init\x18\x01 \x01(\x0b\x32\x13.tts.v1.InitRequestH\x00\x12!\n\x04text\x18\x02 \x01(\x0b\x32\x11.tts.v1.TextChunkH\x00\x12(\n\x08\x63omplete\x18\x03 \x01(\x0b\x32\x14.tts.v1.TextCompleteH\x00\x42\t\n\x07request\"\xbb\x01\n\x0bInitRequest\x12\x11\n\ttask_type\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x11\n\tref_audio\x18\x03 \x01(\x0c\x12\x10\n\x08ref_text\x18\x04 \x01(\t\x12\x15\n\rx_vector_only\x18\x05 \x01(\x08\x12\x0f\n\x07speaker\x18\x06 \x01(\t\x12\x10\n\x08instruct\x18\x07 \x01(\t\x12(\n\x08sampling\x18\n \x01(\x0b\x32\x16.tts.v1.SamplingParams\"\xdb\x01\n\x0eSamplingParams\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\r\n\x05top_p\x18\x03 \x01(\x02\x12\x1a\n\x12repetition_penalty\x18\x04 \x01(\x02\x12\x16\n\x0emax_new_tokens\x18\x05 \x01(\x05\x12\x11\n\tdo_sample\x18\x06 \x01(\x08\x12\x1d\n\x15subtalker_temperature\x18\x07 \x01(\x02\x12\x17\n\x0fsubtalker_top_k\x18\x08 \x01(\x05\x12\x17\n\x0fsubtalker_top_p\x18\t \x01(\x02\"\x19\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x0e\n\x0cTextComplete\"a\n\x0bTTSResponse\x12#\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x12.tts.v1.AudioChunkH\x00\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.tts.v1.TTSErrorH\x00\x42\n\n\x08response\"E\n\nAudioChunk\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08is_final\x18\x03 \x01(\x08\")\n\x08TTSError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2P\n\nTTSService\x12\x42\n\x13StreamingSynthesize\x12\x12.tts.v1.TTSRequest\x1a\x13.tts.v1.TTSResponse(\x01\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_TTSREQUEST']._serialized_start=36
  _globals['_TTSREQUEST']._serialized_end=173
  _globals['_INITREQUEST']._serialized_start=176
  _globals['_INITREQUEST']._serialized_end=363
  _globals['_SAMPLINGPARAMS']._serialized_start=366
  _globals['_SAMPLINGPARAMS']._serialized_end=585
  _globals['_TEXTCHUNK']._serialized_start=587
  _globals['_TEXTCHUNK']._serialized_end=612
  _globals['_TEXTCOMPLETE']._serialized_start=614
  _globals['_TEXTCOMPLETE']._serialized_end=628
  _globals['_TTSRESPONSE']._serialized_start=630
  _globals['_TTSRESPONSE']._serialized_end=727
  _globals['_AUDIOCHUNK']._serialized_start=729
  _globals['_AUDIOCHUNK']._serialized_end=798
  _globals['_TTSERROR']._serialized_start=800
  _globals['_TTSERROR']._serialized_end=841
  _globals['_TTSSERVICE']._serialized_start=843
  _globals['_TTSSERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
