#!/usr/bin/env python3
"""
TTS Gateway — gRPC server that bridges TTSService to Triton tts_orchestrator.

Run from gateway/: python server.py [--triton host:port] [--port 50051]
Requires: Triton server with tts_orchestrator loaded; generate proto first (see README).
"""

import argparse
import base64
import json
import logging
import sys
import time
from typing import Iterator

import grpc
import numpy as np

# Generated by: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/tts_service.proto
from proto import tts_service_pb2 as pb
from proto import tts_service_pb2_grpc as pb_grpc

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("gateway")

SAMPLE_RATE = 24000
TRITON_MODEL = "tts_orchestrator"


def _req_dict_from_init(init: pb.InitRequest, text: str) -> dict:
    """Build orchestrator JSON request from InitRequest + concatenated text."""
    req = {
        "task_type": init.task_type or "voice_design",
        "language": init.language or "auto",
        "text": text,
    }
    if init.ref_audio:
        req["ref_audio"] = base64.b64encode(init.ref_audio).decode("ascii")
    if init.ref_text:
        req["ref_text"] = init.ref_text
    if init.x_vector_only:
        req["x_vector_only"] = True
    if init.speaker:
        req["speaker"] = init.speaker
    if init.instruct:
        req["instruct"] = init.instruct
    return req


def _call_triton_stream(triton_url: str, req_dict: dict) -> Iterator[tuple[bytes, bool]]:
    """Call Triton tts_orchestrator and yield (pcm_bytes, is_final)."""
    try:
        import tritonclient.grpc as grpcclient
    except ImportError:
        raise RuntimeError("tritonclient[grpc] not installed")
    client = grpcclient.InferenceServerClient(url=triton_url)
    if not client.is_server_ready():
        raise RuntimeError(f"Triton not ready at {triton_url}")
    req_json = json.dumps(req_dict)
    req_input = grpcclient.InferInput("request", [1], "BYTES")
    req_input.set_data_from_numpy(np.array([req_json], dtype=object))
    audio_out = grpcclient.InferRequestedOutput("audio_chunk")
    final_out = grpcclient.InferRequestedOutput("is_final")
    chunks = []
    first_ts = [None]
    errors = []

    def callback(result, error):
        if error:
            errors.append(str(error))
            return
        if first_ts[0] is None:
            first_ts[0] = time.perf_counter()
        audio = result.as_numpy("audio_chunk")
        is_final = result.as_numpy("is_final")
        chunks.append((audio.flatten(), bool(is_final.flatten()[0]) if is_final is not None and is_final.size else False))

    client.start_stream(callback=callback)
    client.async_stream_infer(model_name=TRITON_MODEL, inputs=[req_input], outputs=[audio_out, final_out])
    timeout = 120
    t0 = time.perf_counter()
    while (time.perf_counter() - t0) < timeout:
        if errors:
            client.stop_stream()
            raise RuntimeError(errors[0])
        while chunks:
            c, is_final = chunks.pop(0)
            yield c, is_final
            if is_final:
                client.stop_stream()
                return
        time.sleep(0.02)
    client.stop_stream()
    raise RuntimeError("Triton stream timeout")


def _float32_to_pcm16(audio: np.ndarray) -> bytes:
    """Convert float32 [-1,1] to PCM16 LE bytes."""
    audio = np.clip(audio, -1.0, 1.0)
    pcm = (audio * 32767).astype(np.int16)
    return pcm.tobytes()


class TTSGatewayServicer(pb_grpc.TTSServiceServicer):
    def __init__(self, triton_url: str):
        self.triton_url = triton_url

    def StreamingSynthesize(self, request_iterator: Iterator[pb.TTSRequest], context: grpc.ServicerContext) -> Iterator[pb.TTSResponse]:
        init = None
        text_parts = []
        for req in request_iterator:
            if req.HasField("init"):
                init = req.init
            elif req.HasField("text"):
                text_parts.append(req.text.text or "")
            elif req.HasField("complete"):
                break
        if init is None:
            yield pb.TTSResponse(error=pb.TTSError(code=400, message="missing InitRequest"))
            return
        text = "".join(text_parts).strip()
        if not text:
            yield pb.TTSResponse(error=pb.TTSError(code=400, message="no text (send TextChunk before TextComplete)"))
            return
        try:
            req_dict = _req_dict_from_init(init, text)
            for audio_f32, is_final in _call_triton_stream(self.triton_url, req_dict):
                pcm_bytes = _float32_to_pcm16(audio_f32)
                yield pb.TTSResponse(audio=pb.AudioChunk(pcm_data=pcm_bytes, sample_rate=SAMPLE_RATE, is_final=is_final))
        except Exception as e:
            logger.exception("Triton stream failed")
            yield pb.TTSResponse(error=pb.TTSError(code=500, message=str(e)))


def main():
    p = argparse.ArgumentParser(description="TTS Gateway (gRPC -> Triton)")
    p.add_argument("--triton", default="localhost:8001", help="Triton gRPC address")
    p.add_argument("--port", type=int, default=50051, help="Gateway listen port")
    args = p.parse_args()
    server = grpc.server()
    pb_grpc.add_TTSServiceServicer_to_server(TTSGatewayServicer(args.triton), server)
    server.add_insecure_port(f"[::]:{args.port}")
    server.start()
    logger.info("TTS Gateway listening on 0.0.0.0:%s (Triton %s)", args.port, args.triton)
    server.wait_for_termination()


if __name__ == "__main__":
    main()
