"""Prefix KV Cache: cross-request reuse of system prompt KV.

For custom_voice / voice_design / xvec tasks, the prefix portion of the
prefill (role tokens + speaker embedding + special tokens) is identical
across requests with the same configuration.  Caching its KV output
eliminates redundant GPU compute.

Cache key = f"{variant}|{task_type}|{language}|{instruct}|{speaker_or_hash}"
(generated by PrefillBuilder._prefix_cache_key)

Thread safety:
    Accessed only from the engine thread — no locking needed.

Memory:
    Each entry holds one [1, L*2, H, S_prefix, D] talker KV tensor.
    With max_entries=16, S_prefix≈20 tokens, 1.7B model:
    16 × 28×2 × 8 × 20 × 64 × 2 bytes ≈ ~9 MB (negligible)
"""

from __future__ import annotations

import logging
import time
from collections import OrderedDict
from dataclasses import dataclass
from typing import Optional

import torch

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PrefixCacheEntry:
    """Immutable cached prefix KV + metadata."""
    key: str
    talker_kv: torch.Tensor       # [1, L*2, H, S_prefix, D]
    prefix_len: int               # number of tokens in the cached prefix
    created_at: float
    hit_count: int = 0


class PrefixKVCache:
    """LRU cache for prefix KV tensors, keyed by configuration string.

    On hit: caller skips prefill for the cached prefix tokens, feeds only
    the request-specific suffix to the TRT engine, then concatenates the
    cached KV with the new KV output.

    On miss: caller runs full prefill, then calls `put()` to store the
    prefix portion.
    """

    def __init__(self, max_entries: int = 16, max_prefix_len: int = 512):
        self._max_entries = max_entries
        self._max_prefix_len = max_prefix_len
        self._cache: OrderedDict[str, PrefixCacheEntry] = OrderedDict()
        self._total_hits = 0
        self._total_misses = 0

    @property
    def size(self) -> int:
        return len(self._cache)

    @property
    def stats(self) -> dict:
        return {
            "size": self.size,
            "max_entries": self._max_entries,
            "hits": self._total_hits,
            "misses": self._total_misses,
            "hit_rate": (
                self._total_hits / max(1, self._total_hits + self._total_misses)
            ),
        }

    def get(self, key: Optional[str]) -> Optional[PrefixCacheEntry]:
        """Look up a cached prefix.  Returns None on miss."""
        if key is None:
            self._total_misses += 1
            return None

        entry = self._cache.get(key)
        if entry is None:
            self._total_misses += 1
            return None

        self._cache.move_to_end(key)
        self._total_hits += 1
        object.__setattr__(entry, "hit_count", entry.hit_count + 1)
        logger.debug(
            "Prefix cache HIT: key=%s prefix_len=%d (hits=%d)",
            key[:40], entry.prefix_len, entry.hit_count,
        )
        return entry

    def put(
        self,
        key: Optional[str],
        talker_kv: torch.Tensor,
        prefix_len: int,
    ) -> None:
        """Store a prefix KV in the cache.

        Args:
            key: cache key from PrefillBuilder._prefix_cache_key
            talker_kv: [1, L*2, H, prefix_len, D] — the prefix portion of KV
            prefix_len: number of tokens covered by this KV
        """
        if key is None:
            return
        # Server passes max_entries=0 when prefix_cache.enabled is false — never
        # store; avoid LRU loop on an empty OrderedDict (popitem → KeyError).
        if self._max_entries <= 0:
            return
        if prefix_len > self._max_prefix_len:
            logger.debug(
                "Prefix too long (%d > %d), skipping cache", prefix_len, self._max_prefix_len,
            )
            return

        if key in self._cache:
            self._cache.move_to_end(key)
            return

        while len(self._cache) >= self._max_entries:
            evicted_key, evicted = self._cache.popitem(last=False)
            logger.debug(
                "Prefix cache evict: key=%s (hits=%d, age=%.1fs)",
                evicted_key[:40], evicted.hit_count,
                time.monotonic() - evicted.created_at,
            )

        entry = PrefixCacheEntry(
            key=key,
            talker_kv=talker_kv.clone().contiguous(),
            prefix_len=prefix_len,
            created_at=time.monotonic(),
        )
        self._cache[key] = entry
        logger.info(
            "Prefix cache PUT: key=%s prefix_len=%d (size=%d/%d)",
            key[:40], prefix_len, len(self._cache), self._max_entries,
        )

    def invalidate(self, key: str) -> bool:
        """Remove a specific entry.  Returns True if it existed."""
        entry = self._cache.pop(key, None)
        return entry is not None

    def clear(self) -> None:
        """Drop all cached entries."""
        count = len(self._cache)
        self._cache.clear()
        logger.info("Prefix cache cleared (%d entries)", count)
